# Generated by Django 3.2.18 on 2023-03-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('WL', 'weight loss'), ('WG', 'weight gain'), ('BH', 'better healthy'), ('OT', 'other')], default='OT', max_length=2),
        ),
    ]
