# Generated by Django 3.2.18 on 2023-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nutricionist',
            field=models.CharField(choices=[('Anna', 'Anna Smith'), ('John', 'John Doe')], default='Anna', max_length=4),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('WL', 'Weight Loss'), ('WG', 'Weight Gain'), ('BH', 'Better Healthy'), ('MP', 'Meal Planing'), ('NE', 'Nutrition Education'), ('OT', 'Other')], default='WL', max_length=2),
        ),
    ]
