# Generated by Django 3.2.18 on 2023-05-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='nutricionist',
            new_name='nutritionist',
        ),
    ]
